//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamRajyaCrasmibWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MembersMaster
    {
        public string MemberID { get; set; }
        public string Name { get; set; }
        public string ParantName { get; set; }
        public string DOB { get; set; }
        public int Qualification { get; set; }
        public string Occupation { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string P_Address { get; set; }
        public string Permanent_Address { get; set; }
        public string Interest_Achievement { get; set; }
        public string PurposeOfJoining { get; set; }
        public bool OtherNGO_Member { get; set; }
        public string OtherNGOMembersDetails { get; set; }
        public int MembershipCategory { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string Organization { get; set; }
        public string Position { get; set; }
        public string OrganizationPhone { get; set; }
        public string OrganizationFax { get; set; }
        public string OrganizationEmail { get; set; }
        public string OrganizationWebsite { get; set; }
        public string Remarks { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.DateTime> ValidityFrom { get; set; }
        public Nullable<System.DateTime> ValidtyTo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
        public int Gender { get; set; }
    
        public virtual M_MasterInfo M_MasterInfo { get; set; }
        public virtual M_MasterInfo M_MasterInfo1 { get; set; }
    }
}
